server:
  port: 8084
  
# spring cloud gateway requires Netty Runtime
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/** 
           
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**   
#        to provide multiple URl's, in Path= we have to add "," and mention the Url i.e. Path= /hotels/**,/staffing/**
# Eureka Configuration
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
# Okta Configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-21471149.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9ba4kr7gaqbn0Y5d7
    client-secret: Bya9OiW9subfQ982lRrWw9G0FsksrsxavMse-G73
    scopes: openid, emial, profile,offline_access
    
     